### ISSUE TITLE
 j() is undefined

### ISSUE THREAD

**Issue by ganpat-addweb** [smastrom/notivue#15]
i import the usePush in vue js composable 

`import { usePush } from 'notivue'
import { ref } from 'vue'

const errorMessage = ref('')

export const parseError = (debugMessage: string) => {
  const pushData = usePush()
  console.log('🚀 -> 🌏 ~ file: useDebugErrorMessage.ts:9 ~ parseError ~ pushData:', pushData)
  console.log('🚀 -> 🌏 ~ file: useDebugErrorMessage.ts:9 ~ parseError ~ debugMessage:', debugMessage)
  try {
    const errorDetails = JSON.parse(debugMessage)
    for (const key in errorDetails) {
      if (errorDetails[key].length > 0) {
        errorMessage.value = errorDetails[key][0]
        // pushData.error(errorMessage.value)
        pushData.success('Event successfully created')
      }
    }
  } catch (error) {
    // errorMessage.value = 'An error occurred.'
    pushData.error('An error occurred.')
  }
}
`

![image](https://github.com/smastrom/notivue/assets/108649182/6c734093-2982-4a37-b59d-5cf5ad1d724e)

**Comment by smastrom** [comment]
Hi @ganpat-addweb, as stated in the official documentation, to declare the push logic outside your components you have two choices. 

What is important is that you call usePush() in the setup function.

### Solution 1 - Using a composable

```ts
import { usePush } from 'notivue'
import { ref } from 'vue'

export function useParseError() {
   let errorMessage = ''

   const push = usePush() // Call usePush outside of parseError!

   const parseError = (debugMessage: string) => {
      try {
         const errorDetails = JSON.parse(debugMessage)
         for (const key in errorDetails) {
            if (errorDetails[key].length > 0) {
               errorMessage = errorDetails[key][0]
               push.success('Event successfully created')
            }
         }
      } catch (error) {
         push.error(errorMessage)
      }
   }

   return { parseError }
}
```

Then in your components:

```vue
<script setup>
import { useParseError } from './useParseError'

const { parseError } = useParseError()

// call parseError(debugMessage) wherever you want
</script>
```

In this scenario, when you call useParseError() it calls usePush() in the setup function "for you" when the component mounts, only once for the entire lifecycle. The operation succeeds, so parseError() can access it whenever you call it.

In the code you provided, you were calling usePush() inside parseError() which may not have always access to the setup context.

### Solution 2 - Passing the push object

**parseError.ts**
```ts
import type { Push } from 'notivue'

export const parseError = (debugMessage: string, push: Push) => {
   let errorMessage = ''

   try {
      const errorDetails = JSON.parse(debugMessage)
      for (const key in errorDetails) {
         if (errorDetails[key].length > 0) {
            errorMessage = errorDetails[key][0]
            push.success('Event successfully created')
         }
      }
   } catch (error) {
      push.error(errorMessage)
   }
}
```

Then in your components:


```vue
<script setup>
import { usePush } from './usePush'
import { parseError } from './parseError'

const push = usePush()

// call parseError(debugMessage, push) wherever you want
</script>
```

**Comment by ganpat-addweb** [comment]
thank you so much @smastrom
