### ISSUE TITLE
Need help with Nuxt 3 installation

### ISSUE THREAD

**Issue by MogliCodes** [smastrom/notivue#2]
Hi there!

I saw your post on Reddit and immediately wanted to try out Notivue in a Nuxt 3 application. I followed the guidelines in the Nuxt 3 docs and added a plugin file:

plugins/notivue.client.js
```
import { notivue } from 'notivue'

import 'notivue/notifications.css'
import 'notivue/animations.css'

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.use(notivue).mount('#app')
})
```

Then I followed step 2 and 3 from your documentation. When I open the app in the browser I get this error:

`Cannot read properties of undefined (reading 'push')`

Some additional info about the Nuxt app:

```
------------------------------
- Operating System: `Darwin`
- Node Version:     `v18.15.0`
- Nuxt Version:     `3.2.2`
- Nitro Version:    `2.2.3`
- Package Manager:  `pnpm@8.2.0`
- Builder:          `vite`
- User Config:      `app`, `modules`, `supabase`, `pinia`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.4.1`, `@nuxtjs/supabase@0.3.1`, `@pinia/nuxt@0.4.7`
- Build Modules:    `-`
------------------------------
```

**Comment by smastrom** [comment]
Hi Mogli, I suspect that you're not calling _usePush_ in the _setup_ function of your component as displayed in the [Quick Start](https://notivuedocs.netlify.app/quick-start/your-first-notification.html#your-first-notification) section.

```vue
<script setup>
import { usePush } from 'notivue'

const push = usePush()
</script>
```

[Here](https://stackblitz.com/edit/nuxt-starter-fnhcmx?file=pages/index.vue), a working example on Nuxt 3 using StackBlitz.

Please, let me know if everything's sorted out.
