### ISSUE TITLE
`promise` method not working with `enqueue`

### ISSUE THREAD

**Issue by JoaoPedroAS51** [smastrom/notivue#21]
Hey! Thank you for your awesome lib! :)

Just facing one issue since v1.3.0. The `promise` method is not working with `enqueue`. The `resolve` and `reject` don't change the state of the notification, it just remain in loading state forever.

### Repro:
In the notivue demo, enable enqueue and push a promise notification.

![image](https://github.com/smastrom/notivue/assets/15177236/05e33113-ddb6-4299-ba75-e956df908393)

**Comment by smastrom** [comment]
HI @JoaoPedroAS51, thank you very much for reporting!

Please update notivue to the latest version:

`pnpm add notivue@latest`

And thank you again!
