### ISSUE TITLE
Promise resolve/reject toast disappearing

### ISSUE THREAD

**Issue by JoaoPedroAS51** [smastrom/notivue#25]
Hi! I'm facing an issue with the promise toast.

Let's say I have set a duration of 2000ms to my toasts. If the promise takes longer than 2000ms, when I call resolve/reject, the success/error toast disappear immediately.

Note: the loading toast don't disappear because it's set to Infinity

**Comment by smastrom** [comment]
Hi @JoaoPedroAS51, most likely someone already faced this critical issue in the past and didn't reported. But you did, so thank you, seriously.

Please update to latest version:

```bash
pnpm add notivue@latest
```

**Comment by smastrom** [comment]
Hi @JoaoPedroAS51, most likely someone already faced this critical issue in the past and didn't reported. But you did, so thank you, seriously.

Please update to latest version:

```bash
pnpm add notivue@latest
```

And thank you again.

**Comment by JoaoPedroAS51** [comment]
Hey! Thank you for the quick fix! Glad I could help in some way. And thank you so much for your awesome lib! :)
