### ISSUE TITLE
teleportTo does not work with HTML Element.

### ISSUE THREAD

**Issue by luxterful** [smastrom/notivue#33]
When is pass an HTML Element to the `teleportTo` property in the config, it does not work.

I have analysed the code a bit and I guess the problem is the `mergeDeep` function. There is no check in it if the passed Element is an HTML Element, and therefore it is interpreted as an Object which will then be "ripped apart".

A quick fix would be to add a condition like `&& source[key].nodeType !== 1` in the `mergeDeep` function like:

``` typescript
export function mergeDeep<T>(target: T, source: Record<string, any>): T {
   const merged: T = { ...target }

   for (const key in source) {
      if (source.hasOwnProperty(key)) {
         if (source[key] && typeof source[key] === 'object' && source[key].nodeType !== 1) {
            merged[key as keyof T] = mergeDeep(target[key as keyof T], source[key]) as T[keyof T]
         } else {
            merged[key as keyof T] = source[key]
         }
      }
   }

   return merged
}
```

**Comment by luxterful** [comment]
The added condition does the same as the [lodash isElemenet function](https://github.com/lodash/lodash/blob/4.17.15/lodash.js#L11442).

**Comment by smastrom** [comment]
Thank you for reporting, this is indeed a bug. I will release a fix in the next version.

**Comment by luxterful** [comment]
@smastrom all right! Thank you very much!
