### ISSUE TITLE
[Feature]: add `expand` prop

### ISSUE THREAD

**Issue by sadeghbarati** [smastrom/notivue#44]
Expand animation just like in sonner libs https://vue-sonner.vercel.app/

I found this library more advanced and more customizable than `vue-sonner` Can you add `expand` feature to this lib?

Adding `Headless` toasts is much easier in `Notivue`, it would be nice to add this lib to `shadcn-vue` :pray:

**Comment by sadeghbarati** [comment]
Sry just saw this https://github.com/smastrom/notivue/issues/43

**Comment by smastrom** [comment]
> Sry just saw this #43

HI @sadeghbarati, no problem. I totally get that the sonner-like repositioning experience is super appealing and would be nice to have it in Notivue. But as I said in the quoted issue, I just don't think it's a good fit for this package.

Anyways, thanks again for your interest in Notivue and I hope you keep enjoying it. Cheers!
