### ISSUE TITLE
Feature: add the type (sucess,error,..etc) to the options ?

### ISSUE THREAD

**Issue by peter-emad99** [smastrom/notivue#46]
i don't know if this exist but not mentioned in docs ...it will be useful to be able to use push({tyep:'info"}) ..and customize the default type globally in plugin option

**Comment by smastrom** [comment]
That's not currently possible unfortunately. Also, implementing what you're suggesting right now would twist the whole API by creating confusion.

**Comment by smastrom** [comment]
That's not currently possible unfortunately. Also, implementing what you're suggesting right now would twist the whole API by creating confusion. 

However, thank you very much for your suggestion, I hope you'll keep enojoying Notivue. Cheers!

**Comment by smastrom** [comment]
That's not currently possible unfortunately. Also, implementing what you're suggesting would twist the whole API and create confusion.

However, thank you very much for your interest and I hope you'll keep enojoying Notivue. Cheers!

**Comment by smastrom** [comment]
That's not currently possible unfortunately. Also, implementing what you're suggesting would twist the whole API and create confusion.

However, you can always create a tiny function on top of `push` that accepts the type in addition to the usual options:

```ts
import { push as _push, type PushOptions, type NotificationType } from 'notivue'

// Do not allow methods that do not push fresh notification and add the 'load' alias
type AllowedTypes =
   | Exclude<NotificationType, 'clearAll' | 'destroyAll' | 'promise-resolve' | 'promise-reject'>
   | 'load'

function push(options: PushOptions & { type: AllowedTypes }) {
   // Handle 'load' alias
   const type = options.type === 'load' ? 'promise' : options.type

   return _push[type](options)
}

// Add clear methods
push.clearAll = _push.clearAll
push.destroyAll = _push.destroyAll
```

And use it without calling any method when creating fresh notifications by passing the type as option:

```ts
push({
  type: 'info',
  message: 'Hello!',
})

const notification = push({
  type: 'promise', // or 'load'
  message: 'Hello!',
})

notification.resolve('Success') // Or notifcation.success('Success')

push.clearAll()
push.destroyAll()
```

That said, thank you very much for your interest and I hope you'll keep enojoying Notivue. Cheers!

**Comment by smastrom** [comment]
That's not currently possible unfortunately. Also, implementing what you're suggesting would twist the whole API and create confusion.

However, you can always create a tiny function on top of `push` that accepts the type in addition to the usual options:

**src/utils/push.ts**
```ts
import { push as _push, type PushOptions, type NotificationType } from 'notivue'

// Do not allow methods that do not push fresh notification and add the 'load' alias
type AllowedTypes =
   | Exclude<NotificationType, 'clearAll' | 'destroyAll' | 'promise-resolve' | 'promise-reject'>
   | 'load'

export function push(options: PushOptions & { type: AllowedTypes }) {
   // Handle 'load' alias
   const type = options.type === 'load' ? 'promise' : options.type

   return _push[type](options)
}

// Add clear methods
push.clearAll = _push.clearAll
push.destroyAll = _push.destroyAll
```

And use it without calling any method when creating fresh notifications by passing the type as option:

```ts
import { push } from '@/utils/push'

push({
  type: 'info',
  message: 'Hello!',
})

const notification = push({
  type: 'promise', // or 'load'
  message: 'Hello!',
})

notification.resolve('Success') // Or notifcation.success('Success')

push.clearAll()
push.destroyAll()
```

That said, thank you very much for your interest and I hope you'll keep enojoying Notivue. Cheers!

**Comment by smastrom** [comment]
That's not currently possible unfortunately. Also, implementing what you're suggesting would twist the whole API and create confusion.

However, the best you can do is to create a tiny function on top of `push` that accepts the type in addition to the usual options:

**src/utils/push.ts**
```ts
import { push as _push, type PushOptions, type NotificationType } from 'notivue'

// Do not allow methods that do not push fresh notification and add the 'load' alias
type AllowedTypes =
   | Exclude<NotificationType, 'clearAll' | 'destroyAll' | 'promise-resolve' | 'promise-reject'>
   | 'load'

export function push(options: PushOptions & { type: AllowedTypes }) {
   // Handle 'load' alias
   const type = options.type === 'load' ? 'promise' : options.type

   return _push[type](options)
}

// Add clear methods
push.clearAll = _push.clearAll
push.destroyAll = _push.destroyAll
```

And use it without calling any method when creating fresh notifications by passing the type as option:

```ts
import { push } from '@/utils/push'

push({
  type: 'info',
  message: 'Hello!',
})

const notification = push({
  type: 'promise', // or 'load'
  message: 'Hello!',
})

notification.resolve('Success') // Or notifcation.success('Success')

push.clearAll()
push.destroyAll()
```

That said, thank you very much for your interest and I hope you'll keep enojoying Notivue. Cheers!

**Comment by peter-emad99** [comment]
thanks ... i like the package api, and how flexible is it
