### ISSUE TITLE
CSS imports not working with Webpack / Vue CLI

### ISSUE THREAD

**Issue by jfnando3030** [smastrom/notivue#54]
Hello, I am using your library in a Vue3 project but it does not load the CSS, I say this because I check the Chrome console and see that the styles are not loading.
I import the css (import 'notivue/notification.css') in the main.js file

Could you help me solve this error?

**Comment by smastrom** [comment]
Hi @jfnando3030, check this out: https://stackblitz.com/edit/vitejs-vite-h8x1an?file=src%2Fmain.ts. It should work 100%.

Notivue exports both `notification.css` and `notifications.css` which point to the same file.

Which version of Notivue are you using? Are you using any other bundler than Vite?

**Comment by jfnando3030** [comment]
![notification](https://github.com/smastrom/notivue/assets/46821281/f895a8ce-aff5-4061-b3f9-69aa849068a7)

I attach an image, for example in the Notivue__notification class it does not show any CSS, for this reason, the notification is seen without styles.

In my main.js file if I am importing the css like
import 'notivue/notifications.css'

**Comment by jfnando3030** [comment]
I am not using vite, it is a project only with vue 3

**Comment by smastrom** [comment]
Sorry but what does it mean "it is a project with only Vue 3?".

**Comment by smastrom** [comment]
Sorry but what does it mean "it is a project with only Vue 3?".

If you have a main.js file and you installed notivue via NPM, you must be defintely using a bundler. If it's Vite/Parcel the CSS import should work. Not sure about Webpack since I stopped used it years ago.

**Comment by smastrom** [comment]
Sorry but what does it mean "it is a project with only Vue 3?".

If you have a main.js file and you installed notivue via NPM, you must be defintely using a bundler. If it's Vite/Parcel the CSS import should work. Not sure about Webpack since I stopped using it years ago.

**Comment by jfnando3030** [comment]
Yes, I am using Webpack in my project

**Comment by smastrom** [comment]
Ok so if you're using Webpack, the foilowing imports should work:

```js
import "notivue/dist/Notifications/notifications.css"
import "notivue/dist/core/animations.css"
import "notivue/dist/Notifications/notifications-progress.css"
```

The last one is optional and only needed if using the built-in [ProgressBar](https://docs.notivue.smastrom.io/built-in-notifications/progress-bar.html).

**Comment by jfnando3030** [comment]
I got these 2 import errors

ERROR in ./src/main.js 22:0-54
Module not found: Error: Package path ./dist/Notifications/notifications.css is not exported from package C:\xampp2\htdocs\rommies\front_roomies\node_modules\notivue (see exports field in C:\xampp2\htdocs\rommies\front_roomies\node_modules\notivue\package.json)

ERROR in ./src/main.js 23:0-42
Module not found: Error: Package path ./dist/core/animations.css is not exported from package C:\xampp2\htdocs\rommies\front_roomies\node_modules\notivue (see exports field in C:\xampp2\htdocs\rommies\front_roomies\node_modules\notivue\package.json)

**Comment by smastrom** [comment]
Ok, I tested it now with Vue CLI and it should work. Run this command from your project folder:

```shell
npm i webpack@latest
```

Then add the imports inside App.vue at the top of the style tag (below the template):

```vue
<style>
@import "notivue/notifications.css";
@import "notivue/animations.css";
</style>
```

**Comment by smastrom** [comment]
Ok, I tested it now with Vue CLI and it should work. Run this command from your project folder:

```shell
npm i webpack@latest
```

Then add the imports inside App.vue at the top of the style tag (below the template):

```vue
<style>
@import "notivue/notification.css";
@import "notivue/animations.css";
</style>
```

This is the first time I personally try Notivue with Webpack and it seems that the CSS must be imported like this.

Most likely there's a way to make it work from main.js but the last thing I want to do is to deal with Webpack and its docs right now so I will document how to import the CSS in the documentation. 

Thank you very much for raising this issue and have fun!

**Comment by smastrom** [comment]
Ok, I tested it now with Vue CLI and it should work. Run this command from your project folder:

```shell
npm i webpack@latest
```

Then add the imports inside App.vue at the top of the style tag (below the template):

```vue
<style>
@import "notivue/notification.css";
@import "notivue/animations.css";
</style>
```

This is the first time I personally try Notivue with Webpack and it seems that the CSS must be imported like this so thank you for raising the issue.

Most likely there's a way to make it work from main.js but the last thing I want to do is to deal with Webpack and its docs right now so I will document the above in the Notivue documentation.

If it works, please feel free to close the issue and don't forget to have fun!

**Comment by smastrom** [comment]
Ok, I tested it now with Vue CLI and it should work. Run this command from your project folder:

```shell
npm i webpack@latest
```

Then remove any of the previous imports in the app entry point and add the following ones inside App.vue at the top of the style tag (below the template):

```vue
<style>
@import "notivue/notification.css";
@import "notivue/animations.css";
</style>
```

This is the first time I personally try Notivue with Webpack and it seems that the CSS must be imported like this so thank you for raising the issue.

Most likely there's a way to make it work from main.js but the last thing I want to do is to deal with Webpack and its docs right now so I will document the above in the Notivue documentation.

If it works, please feel free to close the issue and don't forget to have fun!

**Comment by jfnando3030** [comment]
Thank you very much, it works perfectly, another error was also solved that did not hide the notification nor did it close with the click event

Thank you again
