### ISSUE TITLE
Cannot start nuxt: Cannot find module 'node_modules\notivue\shared\exports'

### ISSUE THREAD

**Issue by github19938** [smastrom/notivue#57]
Cannot start nuxt:  Cannot find module 'D:\mile\test\node_modules\notivue\shared\exports' imported 
from D:\mile\text\node_modules\notivue\nuxt\module.mjs

my nuxt version:nuxt": "^3.0.0

**Comment by smastrom** [comment]
Hi @github19938, in order to use Notivue's Nuxt module your Nuxt version must be at least `3.5.0`. Check the official Nuxt [upgrade guide](https://nuxt.com/docs/getting-started/upgrade) to see how to upgrade it.

**Comment by github19938** [comment]
thank you，This problem has been solved

Usage with nuxt options api？
"nuxt": "^3.11.2"
 "notivue": "^2.4.4",

**Comment by smastrom** [comment]
Hi @github19938, glad to hear it has been solved.

Even with Options API, `push` is auto-imported in your components so you just need to call it:

```vue
<script>
export default {
  methods: {
    doSomething() {
      push.info('We did something!');
    },
  },
};
</script>

<template>
  <button @click="doSomething">Do something</button>
  <button @click="push.success('Something good has been pushed!')">Push</button>
</template>
```

If for any reason you prefer to state the import or to rename it, you can do that as well:

```js
import { push as notify } from 'notivue'
```

Have a good one and enjoy!
