### ISSUE TITLE
Positioning individual notifications

### ISSUE THREAD

**Issue by alvaro-canepa** [smastrom/notivue#59]
Hi, thanks for this great library! excellent work.

Is there any way to position one notification without setting up global config?   
I want to stay almost all notifications on "top-center", but I need to made some promise notifications on "bottom-right" position. 
At now, I use `updateConfig({ position: 'bottom-right' });` and restore position on resolve. But any success, info, error notification that be fired before promise resolve, will be display on bottom right, instead of top center. 

thanks!

**Comment by smastrom** [comment]
Hi @alvaro-canepa, unfortunately it is not possible to display two streams at the same time. The best you can do is to [temporarily enable the queue](https://docs.notivue.smastrom.io/more-info/troubleshooting.html#i-want-to-push-a-specific-notification-in-a-position-position-different-than-my-config) before pushing the promise's one and then disable it after dismissal.

**Comment by alvaro-canepa** [comment]
Thanks @smastrom   
I see there is only one global container that control the position. 

**Maybe something to consider in the future ;)**
