### ISSUE TITLE
Notifications are hiding under modals, it should be appear on top of everything?

### ISSUE THREAD

**Issue by shihab-jamil** [smastrom/notivue#60]

**Comment by smastrom** [comment]
Hi @shihab-jamil, by default the notifications stream has a default [z-index](https://developer.mozilla.org/en-US/docs/Web/CSS/z-index) set to `500`.

Probably, your modal has a z-index higher than 500, so you should increase the Notivue z-index to make sure sure it overlaps the modal . Please check the documentation on how to edit it according to your needs: https://docs.notivue.smastrom.io/stream-customization/layout.html#gap-and-z-index

**Comment by smastrom** [comment]
Hi @shihab-jamil, by default the notifications stream has a default [z-index](https://developer.mozilla.org/en-US/docs/Web/CSS/z-index) set to `500`.

Probably, your modal has a z-index higher than 500, so you should increase the Notivue z-index to make sure sure it overlaps the modal . Please check the documentation on how to edit it: https://docs.notivue.smastrom.io/stream-customization/layout.html#gap-and-z-index

**Comment by smastrom** [comment]
Hi @shihab-jamil, by default the notifications stream has a "default" [z-index](https://developer.mozilla.org/en-US/docs/Web/CSS/z-index) set to `500`.

Probably, your modal has a z-index higher than 500, so you should set the Notivue z-index to a value higher than the modal one to make sure it overlaps it. Please check the documentation on how to edit it: https://docs.notivue.smastrom.io/stream-customization/layout.html#gap-and-z-index
