### ISSUE TITLE
Issue with Duplicate Detection in Headless Notifications Despite Unique IDs

### ISSUE THREAD

**Issue by FR31NDSDEV** [smastrom/notivue#64]
Hello and thank you for developing this amazing library!

I have successfully implemented the **headless notification** feature as per the documentation. Here's how I'm currently pushing notifications:

```
push.success<HeadlessNotificationProps>({
    id: arg.id,
    props: {
        title: arg.title,
        content: arg.content,
    },
});
```

In my configuration, I have set **avoidDuplicates** to **true**. However, I'm encountering an issue where subsequent notifications are not displayed even when I specify unique IDs for each. This problem does not occur when **avoidDuplicates** is set to **false**.

**Question**: How can I ensure that each headless notification is treated as unique even when **avoidDuplicates** is enabled? Is there a specific property or approach I should be using to differentiate each notification?

Any guidance or insights would be greatly appreciated!

**Comment by smastrom** [comment]
Hi @FR31NDSDEV, notifications are considered duplicates if their `title`, `message` and `type` values are equal.

To avoid unnecessary overhead, Notivue doesn't compare props. Also, there's no need to define an `id` as this is done internally for you after calling `push`.

`title` and/or `message` should be defined outside of `props` also when using Custom Components. They're part of the notification core whereas `props` instead, is just an object that can be optionally used to forward some additional arbitrary data.

When `title` and `message` are not defined (like the snippet you pasted), their value will fallback to an empty string. So when you try to push a second notification, and their value is undefined again, it will be detected as a duplicate as there already are two notification with same `title` and `message`.

To conclude, simply create the notification like this:

```ts
push.success<HeadlessNotificationProps>({
   title: arg.title,   
   message: arg.message,
});
```

or this:

push.success<HeadlessNotificationProps>({
   message: arg.message,
});

**Comment by smastrom** [comment]
Hi @FR31NDSDEV, notifications are considered duplicates if their `title`, `message` and `type` values are equal.

To avoid unnecessary overhead, Notivue doesn't compare props. Also, there's no need to define an `id` as this is done internally for you after calling `push`.

`title` and/or `message` should be defined outside of `props` also when using Custom Components. They're part of the notification core whereas `props` instead, is just an object that can be optionally used to forward some additional arbitrary data.

When `title` and `message` are not defined (like the snippet you pasted), their value will fallback to an empty string. So when you try to push a second notification, and their value is undefined again, it will be detected as a duplicate as there already are two notifications with same `title` and `message`.

To conclude, simply create it like this:

```ts
push.success<HeadlessNotificationProps>({
   title: arg.title,   
   message: arg.message,
});
```

or this:

```ts
push.success<HeadlessNotificationProps>({
   message: arg.message,
});
```

Cheers and enjoy!
