### ISSUE TITLE
Animations doesnt work as expected 

### ISSUE THREAD

**Issue by Nikeweke** [smastrom/notivue#65]
Documentation and try out buttons doesn't show any animation.
https://docs.notivue.smastrom.io/stream-customization/animations.html

**Comment by smastrom** [comment]
Hi @Nikeweke, I can see the notifications on any browser. Perhaps your connection is slow and the JavaScript bundle hasn't been downloaded yet?  

<img width="1792" alt="Screenshot 2024-08-04 alle 22 21 35" src="https://github.com/user-attachments/assets/28153386-872c-4d21-9fd6-4f5ddc117c94">
<img width="1792" alt="Screenshot 2024-08-04 alle 22 21 47" src="https://github.com/user-attachments/assets/fad9b04c-2c9f-40b8-b8a7-5b1e684320db">
<img width="1792" alt="Screenshot 2024-08-04 alle 22 19 51" src="https://github.com/user-attachments/assets/2ed53bd2-b463-4fec-83db-79a043b90388">

**Comment by smastrom** [comment]
Hi @Nikeweke, I can see the notifications on any browser. Perhaps the JavaScript bundle hasn't been downloaded yet?

<img width="1792" alt="Screenshot 2024-08-04 alle 22 21 35" src="https://github.com/user-attachments/assets/28153386-872c-4d21-9fd6-4f5ddc117c94">
<img width="1792" alt="Screenshot 2024-08-04 alle 22 21 47" src="https://github.com/user-attachments/assets/fad9b04c-2c9f-40b8-b8a7-5b1e684320db">
<img width="1792" alt="Screenshot 2024-08-04 alle 22 19 51" src="https://github.com/user-attachments/assets/2ed53bd2-b463-4fec-83db-79a043b90388">
