### ISSUE TITLE
When using `avoidDuplicates`, it would be nice if the order reflects the anouncement time.

### ISSUE THREAD

**Issue by MartenBE** [smastrom/notivue#67]
If you use `avoidDuplicates` and you trigger A B A, then the queue displays A B, which looks like B happened last if the user missed the announcement animation. It would be more intuitive if the first dupe dissapears and the second dupe is shown in the queue so that the last announced notification is at the top (or bottom depending on config) of the queue of notifications.

**Comment by smastrom** [comment]
Sorry but I don't think it will be more intuitive. You can always create a wrapper on top of `push` and manually clear the duplicated notification before pushing it if `type`, `message` and `title` value matches.
