### ISSUE TITLE
Update of already pushed notification

### ISSUE THREAD

**Issue by akrpic77** [smastrom/notivue#68]
Hello,

first  thank you for developing this amazing library!

I have a question, is there a way to update already pushed notification?  

Using same id doesn't work.

**Comment by smastrom** [comment]
Depends on what you're trying to achieve. To update the `title` or `message` value of any notification, pass a string ref and simply update it:

```ts
const message = ref('Hello!')

push.success(message) // Will display 'Hello!'

await doSomething()

message.value = 'Good afternoon!' // Message will be replaced with 'Good afternoon!'
```

Or with dynamic notifications:

```ts
const message = 'Uploading file #1...'

const notification = push.load(message)

await uploadFile()

message.value = 'Uploading file #2'

await uploadFile()

notification.success('All files uploaded!')
```

For anything more complex, you could use [Custom Components](https://docs.notivue.smastrom.io/headless/usage.html) and pass how many refs as you want to the `props` property.

**Comment by akrpic77** [comment]
It work
