### ISSUE TITLE
[FEAT] Display duplicate count

### ISSUE THREAD

**Issue by LIUKQSGITHUB** [smastrom/notivue#70]
After using the avoidDuplicates option, when multiple identical messages are pushed, only one notification is displayed. Is it possible to display the number of current messages on the notification? That is, when multiple messages are sent, the notification will automatically reset the duration and display the number of current duplicate messages. It would be great if it is possible. Thank you.

**Comment by smastrom** [comment]
Hi @LIUKQSGITHUB, the duration is already "reset" when a duplicate is created. For example, if you create a notification with a duration of 3s, and after 2 seconds you push it again, the notification timeout is updated from 1s (remaining) to 3s (initial duration). The notification is also announced again by screen readers.

Regarding displaying the duplicate count, there are no plans on implementing it. By the way, Notivue gives you all the tools to implement it on your own very easily.

To do that, simply access and use `item.duplicateCount` in the default slot. This works the same way with both Built-in Notifications and Custom Components:

[StackBlitz example](https://stackblitz.com/edit/nuxt-starter-cmbeuy?file=app.vue)

![Screenshot 2024-11-09 alle 08 03 28](https://github.com/user-attachments/assets/c889d086-509a-40ca-9eda-8ebc344a2e68)

```vue
<template>
    <Notivue v-slot="item">
      <Notification :item="item">
        <div class="Notivue__duplicateCount" v-if="item.duplicateCount > 0">
          {{ item.duplicateCount }}
        </div>
      </Notification>
    </Notivue>
</template>

<style scoped>
.Notivue__duplicateCount {
  position: absolute;
  top: -0.5rem;
  right: -0.5rem;

  display: flex;
  justify-content: center;
  align-items: center;

  width: 1.25rem;
  height: 1.25rem;
  border-radius: 999px;
  background-color: #f75656;
  color: #fff;

  font-size: 0.725rem;
  font-weight: 600;
  line-height: 1;
}
</style>
```
