### ISSUE TITLE
The source code of demo page

### ISSUE THREAD

**Issue by unkn0wn404** [smastrom/notivue#71]
Hello.
Is it possible to share the source code of the [demo page](https://notivue.smastrom.io/)?
It could help to better understand in practice many features. This page is great for taking a look at what is possible to do with your library (and it's great!), however, not everything is clear when reading only the documentation.
And thank you for developing such a great library.

**Comment by smastrom** [comment]
Hi @unkn0wn404, the source code you're looking for is located in the [playground](https://github.com/smastrom/notivue/tree/main/playground) folder.

Since documentation can always be imporved, can you please elaborate on:

> not everything is clear when reading only the documentation.

And thank you very much for your kind words.

**Comment by smastrom** [comment]
Hi @unkn0wn404, you're welcome, I'm glad you enjoy it.

The source code you're looking for is located in the [playground](https://github.com/smastrom/notivue/tree/main/playground) folder.

Since documentation can always be imporved, can you please elaborate on:

> not everything is clear when reading only the documentation.
